I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/opener.rpy", line 30, in script
    f "This is kind of embarrassing..."
Exception: Sayer 'f' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/opener.rpy", line 30, in script
    f "This is kind of embarrassing..."
  File "E:\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'f' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Project F 1.0
Tue Jul 28 22:11:14 2020
